import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AppShell } from "../components/app-shell";
import { apiFetch } from "../lib/api";
const tabs = ["Profile", "API Keys", "Secrets", "Billing"];
export function SettingsPage() {
    const [tab, setTab] = useState("Profile");
    const meQ = useQuery({ queryKey: ["me"], queryFn: () => apiFetch("/api/user/me") });
    const usageQ = useQuery({ queryKey: ["usage"], queryFn: () => apiFetch("/api/user/usage") });
    const usage = useMemo(() => usageQ.data, [usageQ.data]);
    return (_jsx(AppShell, { title: "Settings", subtitle: "Manage your account, API keys, and billing", children: _jsxs("div", { className: "flex gap-6", children: [_jsx("div", { className: "flex w-[200px] shrink-0 flex-col gap-1", children: tabs.map((item) => (_jsx("button", { type: "button", onClick: () => setTab(item), className: `w-full rounded-lg px-3 py-2.5 text-left text-sm transition-colors ${tab === item
                            ? "bg-[var(--bg-surface)] font-medium text-[var(--text-primary)]"
                            : "text-[var(--text-secondary)] hover:bg-[var(--bg-surface)]"}`, children: item }, item))) }), _jsxs("div", { className: "flex flex-1 flex-col gap-5", children: [tab === "Profile" ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "rounded-xl border border-[var(--divider)] bg-[var(--bg-surface)] p-5", children: [_jsx("h2", { className: "mb-4 text-[15px] font-semibold", children: "Profile Information" }), meQ.isLoading ? _jsx("p", { className: "text-sm text-[var(--text-tertiary)]", children: "Loading..." }) : null, meQ.data ? (_jsxs("div", { className: "flex flex-col gap-4", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("label", { className: "flex flex-col gap-1.5", children: [_jsx("span", { className: "text-xs font-medium text-[var(--text-secondary)]", children: "Name" }), _jsx("input", { className: "w-full rounded-[6px] border border-[var(--divider)] bg-[var(--bg-inset)] px-3.5 py-2.5 text-[13px] focus:border-[var(--accent)] focus:outline-none", defaultValue: meQ.data.name || "", placeholder: "Your name" })] }), _jsxs("label", { className: "flex flex-col gap-1.5", children: [_jsx("span", { className: "text-xs font-medium text-[var(--text-secondary)]", children: "Email" }), _jsx("input", { className: "w-full rounded-[6px] border border-[var(--divider)] bg-[var(--bg-inset)] px-3.5 py-2.5 text-[13px] focus:border-[var(--accent)] focus:outline-none", defaultValue: meQ.data.email, readOnly: true })] })] }), _jsx("button", { type: "button", className: "w-fit rounded-lg bg-[var(--accent)] px-4 py-2 text-sm font-semibold text-[var(--bg-primary)]", children: "Save changes" })] })) : null] }), _jsxs("div", { className: "rounded-xl border border-[var(--divider)] bg-[var(--bg-surface)] p-5", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("h2", { className: "text-[15px] font-semibold", children: "Current Plan" }), _jsx("span", { className: "rounded-full px-2.5 py-0.5 text-[11px] font-semibold capitalize", style: { background: "rgba(34,211,238,0.15)", color: "var(--accent)", fontFamily: "var(--font-mono)" }, children: meQ.data?.plan || "Free" })] }), _jsx("button", { type: "button", className: "rounded-lg border border-[var(--text-muted)] px-4 py-2 text-sm font-medium text-[var(--text-secondary)]", children: "Upgrade Plan" })] }), _jsxs("div", { className: "mt-4", children: [_jsxs("div", { className: "mb-2 flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-[var(--text-secondary)]", children: "Credit usage" }), _jsxs("span", { style: { fontFamily: "var(--font-mono)" }, children: [usage?.credits_used ?? 0, " / ", (usage?.credits_used ?? 0) + (usage?.credits_remaining ?? 0)] })] }), _jsx("div", { className: "h-2 rounded bg-[var(--bg-inset)]", children: _jsx("div", { className: "h-2 rounded bg-[var(--accent)]", style: {
                                                            width: (usage?.credits_used ?? 0) + (usage?.credits_remaining ?? 0) > 0
                                                                ? `${(((usage?.credits_used ?? 0) / ((usage?.credits_used ?? 0) + (usage?.credits_remaining ?? 0))) * 100).toFixed(0)}%`
                                                                : "0%",
                                                        } }) })] })] }), _jsxs("div", { className: "rounded-xl border border-red-500/30 bg-[var(--bg-surface)] p-5", children: [_jsx("h2", { className: "mb-2 text-[15px] font-semibold text-red-400", children: "Danger Zone" }), _jsx("p", { className: "mb-4 text-sm text-[var(--text-tertiary)]", children: "Permanently delete your account and all pipeline data. This cannot be undone." }), _jsx("button", { type: "button", className: "rounded-lg border border-red-500/40 px-4 py-2 text-sm font-medium text-red-300 opacity-60", disabled: true, children: "Delete account" })] })] })) : null, tab === "API Keys" ? (_jsxs("div", { className: "rounded-xl border border-[var(--divider)] bg-[var(--bg-surface)] p-5", children: [_jsx("h2", { className: "mb-2 text-[15px] font-semibold", children: "API Keys" }), _jsx("p", { className: "mb-4 text-sm text-[var(--text-tertiary)]", children: "Manage your API credentials for programmatic access." }), _jsx("button", { type: "button", className: "rounded-lg border border-[var(--divider)] px-4 py-2 text-sm text-[var(--text-secondary)]", children: "Generate key (coming soon)" })] })) : null, tab === "Secrets" ? (_jsxs("div", { className: "rounded-xl border border-[var(--divider)] bg-[var(--bg-surface)] p-5", children: [_jsx("h2", { className: "mb-2 text-[15px] font-semibold", children: "Secrets" }), _jsx("p", { className: "mb-4 text-sm text-[var(--text-tertiary)]", children: "Store provider tokens and secure variables for use in pipelines." }), _jsx("button", { type: "button", className: "rounded-lg border border-[var(--divider)] px-4 py-2 text-sm text-[var(--text-secondary)]", children: "Add secret (coming soon)" })] })) : null, tab === "Billing" ? (_jsxs("div", { className: "rounded-xl border border-[var(--divider)] bg-[var(--bg-surface)] p-5", children: [_jsx("h2", { className: "mb-2 text-[15px] font-semibold", children: "Billing" }), _jsx("p", { className: "mb-4 text-sm text-[var(--text-tertiary)]", children: "View usage and manage your subscription." }), _jsxs("div", { className: "grid grid-cols-4 gap-4", children: [_jsx(Tile, { label: "Credits used", value: String(usage?.credits_used ?? 0) }), _jsx(Tile, { label: "Credits left", value: String(usage?.credits_remaining ?? 0) }), _jsx(Tile, { label: "Runs today", value: String(usage?.runs_today ?? 0) }), _jsx(Tile, { label: "Total cost", value: `€${((usage?.total_cost_cents ?? 0) / 100).toFixed(2)}` })] })] })) : null] })] }) }));
}
function Tile({ label, value }) {
    return (_jsxs("div", { className: "rounded-[10px] border border-[var(--divider)] bg-[var(--bg-inset)] p-4", children: [_jsx("p", { className: "text-[10px] font-semibold uppercase text-[var(--text-tertiary)]", style: { fontFamily: "var(--font-mono)", letterSpacing: "1.5px" }, children: label }), _jsx("p", { className: "mt-2 text-lg font-bold", style: { fontFamily: "var(--font-mono)" }, children: value })] }));
}
//# sourceMappingURL=settings.js.map